export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'

export const FETCH_CART = 'FETCH_CART'
export const GET_TOTAL = 'GET_TOTAL'
export const POST_CARTITEM = 'POST_CARTITEM'
export const DELETE_CARTITEM = 'DELETE_CARTITEM'
export const UPDATE_CARTITEM = 'UPDATE_CARTITEM'

// export const CREATE_USER = 'CREATE_USER'
// export const LOGIN_USER = 'LOGIN_USER'
// export const LOGOUT_USER = 'LOGOUT_USER'
// export const FETCH_USERS = 'FETCH_USERS'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const FAILED_LOGIN = 'FAILED_LOGIN'
export const LOGOUT_USER = 'LOGOUT_USER'
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER'
